### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ksicon** [drupalcommerce/project-base#9] opened 2016-09-27 09:27 UTC
Thanks you for providing a project base with commerce.

Project creation with Composer and project-base was successful.  But the installation both per UI or `drupal site:install commerce_base`  don't function.
The error message is:
`Fatal error: Symfony\Component\ClassLoader\ApcClassLoader::loadClass(): Failed opening required '/var/www/drupal/web/vendor/composer/../symfony/http-foundation/Response.php' (include_path='.:/usr/share/php') in /var/www/drupal/vendor/symfony/class-loader/ApcClassLoader.php on line 110`

**Comment by bojanz** [comment] 2016-09-27 09:28
Are you getting this locally or remotely? If remotely, are you sure you committed all of the files correctly?

I can't reproduce, the file is there on my install.

**Comment by ksicon** [comment] 2016-09-27 09:47
Thanks for the lightning fast reply. 

It is locally in a vm. The files seem to be there:

```
$ ls -la vendor/symfony/http-foundation
total 276
drwxrwxr-x  6 vagrant www-data  4096 Sep 26 22:09 .
drwxrwxr-x 27 vagrant www-data  4096 Sep 26 22:54 ..
-rw-rw-r--  1 vagrant www-data  4912 Sep  6 10:55 AcceptHeaderItem.php
-rw-rw-r--  1 vagrant www-data  3608 Sep  6 10:55 AcceptHeader.php
-rw-rw-r--  1 vagrant www-data   930 Sep  6 10:55 ApacheRequest.php
-rw-rw-r--  1 vagrant www-data 11901 Sep  6 10:55 BinaryFileResponse.php
-rw-rw-r--  1 vagrant www-data  6974 Sep  6 10:55 CHANGELOG.md
-rw-rw-r--  1 vagrant www-data   990 Sep  6 10:55 composer.json
-rw-rw-r--  1 vagrant www-data  5012 Sep  6 10:55 Cookie.php
drwxrwxr-x  2 vagrant www-data  4096 Sep  6 10:55 Exception
-rw-rw-r--  1 vagrant www-data  1359 Sep  6 10:55 ExpressionRequestMatcher.php
drwxrwxr-x  4 vagrant www-data  4096 Sep  6 10:55 File
-rw-rw-r--  1 vagrant www-data  3915 Sep  6 10:55 FileBag.php
-rw-rw-r--  1 vagrant www-data    34 Sep  6 10:55 .gitignore
-rw-rw-r--  1 vagrant www-data  8664 Sep  6 10:55 HeaderBag.php
-rw-rw-r--  1 vagrant www-data  3918 Sep  6 10:55 IpUtils.php
-rw-rw-r--  1 vagrant www-data  6968 Sep  6 10:55 JsonResponse.php
-rw-rw-r--  1 vagrant www-data  1065 Sep  6 10:55 LICENSE
-rw-rw-r--  1 vagrant www-data  9299 Sep  6 10:55 ParameterBag.php
-rw-rw-r--  1 vagrant www-data   834 Sep  6 10:55 phpunit.xml.dist
-rw-rw-r--  1 vagrant www-data   537 Sep  6 10:55 README.md
-rw-rw-r--  1 vagrant www-data  2624 Sep  6 10:55 RedirectResponse.php
-rw-rw-r--  1 vagrant www-data   758 Sep  6 10:55 RequestMatcherInterface.php
-rw-rw-r--  1 vagrant www-data  4326 Sep  6 10:55 RequestMatcher.php
-rw-rw-r--  1 vagrant www-data 63397 Sep  6 10:55 Request.php
-rw-rw-r--  1 vagrant www-data  2358 Sep  6 10:55 RequestStack.php
-rw-rw-r--  1 vagrant www-data  8777 Sep  6 10:55 ResponseHeaderBag.php
-rw-rw-r--  1 vagrant www-data 35386 Sep  6 10:55 Response.php
-rw-rw-r--  1 vagrant www-data  4238 Sep  6 10:55 ServerBag.php
drwxrwxr-x  5 vagrant www-data  4096 Sep  6 10:55 Session
-rw-rw-r--  1 vagrant www-data  2988 Sep  6 10:55 StreamedResponse.php
drwxrwxr-x  4 vagrant www-data  4096 Sep  6 10:55 Tests
```

**Comment by mglaman** [comment] 2016-09-27 10:08
Sounds like the bug Drupal throws when visiting index.php without site
install. Maybe the installed Console is borked?

**Comment by ksicon** [comment] 2016-09-27 10:36
Drupal console seemed to be okay. Anyhow I reinstalled it and got:

```
$ drupal site:install commerce_base
PHP Fatal error:  Uncaught Error: Class 'Drupal\Core\Language\LanguageManager' not found in phar:///usr/local/bin/drupal/src/Utils/Site.php:193
Stack trace:
#0 phar:///usr/local/bin/drupal/src/Command/Site/InstallCommand.php(349): Drupal\Console\Utils\Site->getStandardLanguages()
#1 phar:///usr/local/bin/drupal/src/Command/Site/InstallCommand.php(142): Drupal\Console\Command\Site\InstallCommand->getLanguages()
#2 phar:///usr/local/bin/drupal/vendor/symfony/console/Command/Command.php(244): Drupal\Console\Command\Site\InstallCommand->interact(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Style\DrupalStyle))
#3 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(860): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Style\DrupalStyle))
#4 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Site\InstallCommand), Obj in phar:///usr/local/bin/drupal/src/Utils/Site.php on line 193

Fatal error: Uncaught Error: Class 'Drupal\Core\Language\LanguageManager' not found in phar:///usr/local/bin/drupal/src/Utils/Site.php:193
Stack trace:
#0 phar:///usr/local/bin/drupal/src/Command/Site/InstallCommand.php(349): Drupal\Console\Utils\Site->getStandardLanguages()
#1 phar:///usr/local/bin/drupal/src/Command/Site/InstallCommand.php(142): Drupal\Console\Command\Site\InstallCommand->getLanguages()
#2 phar:///usr/local/bin/drupal/vendor/symfony/console/Command/Command.php(244): Drupal\Console\Command\Site\InstallCommand->interact(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Style\DrupalStyle))
#3 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(860): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Style\DrupalStyle))
#4 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Site\InstallCommand), Obj in phar:///usr/local/bin/drupal/src/Utils/Site.php on line 193

```

**Comment by bojanz** [comment] 2016-09-27 10:46
You are using a global Drupal Console install, which they recommend against. 
The project-base gives you its own Drupal Console in ./bin/drupal, that one might work better?
But you did say you see errors if you use the UI too...

**Comment by ksicon** [comment] 2016-09-27 14:19
Thank you, with local Composer installation process it worked correctly.

**Closed as completed** 2017-07-23 22:11 UTC
